"""Added CompletedIdea table

Revision ID: 49589ca00ae4
Revises: db24bbf1a571
Create Date: 2025-02-22 01:22:49.515444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49589ca00ae4'
down_revision = 'db24bbf1a571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.Column('completion_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['idea.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_idea')
    # ### end Alembic commands ###
