"""Added category admin

Revision ID: 6a21cde88762
Revises: 1c9e7ec5d33a
Create Date: 2025-02-23 11:54:40.757074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a21cde88762'
down_revision = '1c9e7ec5d33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_category_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_category_admin')

    # ### end Alembic commands ###
