"""Added completed_at to CompletedIdea

Revision ID: bde3fa50e40e
Revises: 6a21cde88762
Create Date: 2025-02-24 18:35:44.366642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde3fa50e40e'
down_revision = '6a21cde88762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completed_idea', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
