"""Fix database schema

Revision ID: 9399e44229b9
Revises: 920f2297cf51
Create Date: 2025-02-20 20:46:05.311848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9399e44229b9'
down_revision = '920f2297cf51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_column('categories')

    # ### end Alembic commands ###
